stages:
  - test
  - build

image: node:20-bookworm

backend:test:
  stage: test
  cache:
    key:
      files:
        - src/geoRisco/package-lock.json
    paths:
      - src/geoRisco/.npm/
  script:
    - cd src/geoRisco
    - npm ci --cache .npm --prefer-offline --no-audit
    - npm test

backend:build:
  stage: build
  cache:
    key:
      files:
        - src/geoRisco/package-lock.json
    paths:
      - src/geoRisco/.npm/
  script:
    - cd src/geoRisco
    - npm ci --cache .npm --prefer-offline --no-audit
    - npm run build
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - src/geoRisco/dist/

frontend:build:
  stage: build
  cache:
    key:
      files:
        - src/frontend/package-lock.json
    paths:
      - src/frontend/.npm/
  script:
    - cd src/frontend
    - npm ci --cache .npm --prefer-offline --no-audit
    - npm run build
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - src/frontend/dist/
